// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	pipeline_model "github.com/kubeflow/pipelines/backend/api/go_http_client/pipeline_model"
)

// DeletePipelineByNameReader is a Reader for the DeletePipelineByName structure.
type DeletePipelineByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePipelineByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePipelineByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeletePipelineByNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePipelineByNameOK creates a DeletePipelineByNameOK with default headers values
func NewDeletePipelineByNameOK() *DeletePipelineByNameOK {
	return &DeletePipelineByNameOK{}
}

/*DeletePipelineByNameOK handles this case with default header values.

A successful response.
*/
type DeletePipelineByNameOK struct {
	Payload interface{}
}

func (o *DeletePipelineByNameOK) Error() string {
	return fmt.Sprintf("[DELETE /apis/v1beta1/namespaces/{namespace}/pipelines/{name}][%d] deletePipelineByNameOK  %+v", 200, o.Payload)
}

func (o *DeletePipelineByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePipelineByNameDefault creates a DeletePipelineByNameDefault with default headers values
func NewDeletePipelineByNameDefault(code int) *DeletePipelineByNameDefault {
	return &DeletePipelineByNameDefault{
		_statusCode: code,
	}
}

/*DeletePipelineByNameDefault handles this case with default header values.

DeletePipelineByNameDefault delete pipeline by name default
*/
type DeletePipelineByNameDefault struct {
	_statusCode int

	Payload *pipeline_model.APIStatus
}

// Code gets the status code for the delete pipeline by name default response
func (o *DeletePipelineByNameDefault) Code() int {
	return o._statusCode
}

func (o *DeletePipelineByNameDefault) Error() string {
	return fmt.Sprintf("[DELETE /apis/v1beta1/namespaces/{namespace}/pipelines/{name}][%d] DeletePipelineByName default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePipelineByNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
