// Code generated by go-swagger; DO NOT EDIT.

package job_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListJobsParams creates a new ListJobsParams object
// with the default values initialized.
func NewListJobsParams() *ListJobsParams {
	var ()
	return &ListJobsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListJobsParamsWithTimeout creates a new ListJobsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListJobsParamsWithTimeout(timeout time.Duration) *ListJobsParams {
	var ()
	return &ListJobsParams{

		timeout: timeout,
	}
}

// NewListJobsParamsWithContext creates a new ListJobsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListJobsParamsWithContext(ctx context.Context) *ListJobsParams {
	var ()
	return &ListJobsParams{

		Context: ctx,
	}
}

// NewListJobsParamsWithHTTPClient creates a new ListJobsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListJobsParamsWithHTTPClient(client *http.Client) *ListJobsParams {
	var ()
	return &ListJobsParams{
		HTTPClient: client,
	}
}

/*ListJobsParams contains all the parameters to send to the API endpoint
for the list jobs operation typically these are written to a http.Request
*/
type ListJobsParams struct {

	/*ExperimentID
	  Specify the experiment jobs belong to.

	*/
	ExperimentID string
	/*Filter
	  A url-encoded, JSON-serialized Filter protocol buffer (see
	[filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).

	*/
	Filter *string
	/*Namespace
	  TODO Diana: Checkout this case.
	Filter based on the namespace.

	*/
	Namespace *string
	/*PageSize
	  The number of jobs to be listed per page. If there are more jobs than this
	number, the response message will contain a nextPageToken field you can use
	to fetch the next page.

	*/
	PageSize *int32
	/*PageToken
	  A page token to request the next page of results. The token is acquried
	from the nextPageToken field of the response from the previous
	ListJobs call or can be omitted when fetching the first page.

	*/
	PageToken *string
	/*SortBy
	  Can be format of "field_name", "field_name asc" or "field_name desc".
	Ascending by default.

	*/
	SortBy *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list jobs params
func (o *ListJobsParams) WithTimeout(timeout time.Duration) *ListJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list jobs params
func (o *ListJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list jobs params
func (o *ListJobsParams) WithContext(ctx context.Context) *ListJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list jobs params
func (o *ListJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list jobs params
func (o *ListJobsParams) WithHTTPClient(client *http.Client) *ListJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list jobs params
func (o *ListJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExperimentID adds the experimentID to the list jobs params
func (o *ListJobsParams) WithExperimentID(experimentID string) *ListJobsParams {
	o.SetExperimentID(experimentID)
	return o
}

// SetExperimentID adds the experimentId to the list jobs params
func (o *ListJobsParams) SetExperimentID(experimentID string) {
	o.ExperimentID = experimentID
}

// WithFilter adds the filter to the list jobs params
func (o *ListJobsParams) WithFilter(filter *string) *ListJobsParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the list jobs params
func (o *ListJobsParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithNamespace adds the namespace to the list jobs params
func (o *ListJobsParams) WithNamespace(namespace *string) *ListJobsParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the list jobs params
func (o *ListJobsParams) SetNamespace(namespace *string) {
	o.Namespace = namespace
}

// WithPageSize adds the pageSize to the list jobs params
func (o *ListJobsParams) WithPageSize(pageSize *int32) *ListJobsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list jobs params
func (o *ListJobsParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the list jobs params
func (o *ListJobsParams) WithPageToken(pageToken *string) *ListJobsParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the list jobs params
func (o *ListJobsParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WithSortBy adds the sortBy to the list jobs params
func (o *ListJobsParams) WithSortBy(sortBy *string) *ListJobsParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the list jobs params
func (o *ListJobsParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WriteToRequest writes these params to a swagger request
func (o *ListJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param experiment_id
	if err := r.SetPathParam("experiment_id", o.ExperimentID); err != nil {
		return err
	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if o.Namespace != nil {

		// query param namespace
		var qrNamespace string
		if o.Namespace != nil {
			qrNamespace = *o.Namespace
		}
		qNamespace := qrNamespace
		if qNamespace != "" {
			if err := r.SetQueryParam("namespace", qNamespace); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string
		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {
			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}

	}

	if o.SortBy != nil {

		// query param sort_by
		var qrSortBy string
		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {
			if err := r.SetQueryParam("sort_by", qSortBy); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
