// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: backend/api/storage_states.proto

package go_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperimentStorageState int32

const (
	ExperimentStorageState_STORAGESTATE_UNSPECIFIED ExperimentStorageState = 0
	ExperimentStorageState_STORAGESTATE_AVAILABLE   ExperimentStorageState = 1
	ExperimentStorageState_STORAGESTATE_ARCHIVED    ExperimentStorageState = 2
)

// Enum value maps for ExperimentStorageState.
var (
	ExperimentStorageState_name = map[int32]string{
		0: "STORAGESTATE_UNSPECIFIED",
		1: "STORAGESTATE_AVAILABLE",
		2: "STORAGESTATE_ARCHIVED",
	}
	ExperimentStorageState_value = map[string]int32{
		"STORAGESTATE_UNSPECIFIED": 0,
		"STORAGESTATE_AVAILABLE":   1,
		"STORAGESTATE_ARCHIVED":    2,
	}
)

func (x ExperimentStorageState) Enum() *ExperimentStorageState {
	p := new(ExperimentStorageState)
	*p = x
	return p
}

func (x ExperimentStorageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExperimentStorageState) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_storage_states_proto_enumTypes[0].Descriptor()
}

func (ExperimentStorageState) Type() protoreflect.EnumType {
	return &file_backend_api_storage_states_proto_enumTypes[0]
}

func (x ExperimentStorageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExperimentStorageState.Descriptor instead.
func (ExperimentStorageState) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_storage_states_proto_rawDescGZIP(), []int{0}
}

var File_backend_api_storage_states_proto protoreflect.FileDescriptor

var file_backend_api_storage_states_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x2a, 0x6d, 0x0a, 0x16, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x16, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53,
	0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48,
	0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_api_storage_states_proto_rawDescOnce sync.Once
	file_backend_api_storage_states_proto_rawDescData = file_backend_api_storage_states_proto_rawDesc
)

func file_backend_api_storage_states_proto_rawDescGZIP() []byte {
	file_backend_api_storage_states_proto_rawDescOnce.Do(func() {
		file_backend_api_storage_states_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_api_storage_states_proto_rawDescData)
	})
	return file_backend_api_storage_states_proto_rawDescData
}

var file_backend_api_storage_states_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_api_storage_states_proto_goTypes = []interface{}{
	(ExperimentStorageState)(0), // 0: api.ExperimentStorageState
}
var file_backend_api_storage_states_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_api_storage_states_proto_init() }
func file_backend_api_storage_states_proto_init() {
	if File_backend_api_storage_states_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_api_storage_states_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_api_storage_states_proto_goTypes,
		DependencyIndexes: file_backend_api_storage_states_proto_depIdxs,
		EnumInfos:         file_backend_api_storage_states_proto_enumTypes,
	}.Build()
	File_backend_api_storage_states_proto = out.File
	file_backend_api_storage_states_proto_rawDesc = nil
	file_backend_api_storage_states_proto_goTypes = nil
	file_backend_api_storage_states_proto_depIdxs = nil
}
